# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dwn.xml'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, json
import zipfile as zf
from PyQt5 import QtCore, QtGui, QtWidgets
import requests

ins = 'resources\\pkg\\'
pkgname_gb = 'gb.goldberg'
pkgname_sse = 'sse.smartsteamemu'
langIndex = 0



class Ui_Form(object):
    def setupUi(self, Form):
        from pyrate import lang
        from pyrate import debug

        with open('resources/config/temp.drc', 'r') as temp:
            langIndex = int(temp.read())
        if langIndex == 0:
            self.shortLang = 'en'
        if langIndex == 1:
            self.shortLang = 'de'

        if debug: print('Current Language started:', langIndex)
        Form.setObjectName("Window")
        Form.resize(291, 109)
        Form.setMinimumSize(QtCore.QSize(291, 109))
        Form.setMaximumSize(QtCore.QSize(291, 109))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 20, 291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 111, 20))
        self.label_4.setObjectName("label_4")
        self.goldberg_i = QtWidgets.QLabel(Form)
        self.goldberg_i.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.goldberg_i.setObjectName("goldberg_i")
        self.smartsteamemu_i = QtWidgets.QLabel(Form)
        self.smartsteamemu_i.setGeometry(QtCore.QRect(140, 70, 41, 20))
        self.smartsteamemu_i.setObjectName("smartsteamemu_i")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 40, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 70, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        # Checking Goldberg
        if os.path.exists(ins+pkgname_gb):
            gb_ = lang[self.shortLang][7]
        else: gb_ = lang[self.shortLang][8]

        # Checking SSE
        if os.path.exists(ins+pkgname_sse):
            sse_ = lang[self.shortLang][7]
        else: sse_ = lang[self.shortLang][8]

        self.pushButton.clicked.connect(self.gb_install)
        self.pushButton_2.clicked.connect(self.sse_install)

        self.retranslateUi(Form)
        self.goldberg_i.setText(gb_)
        self.smartsteamemu_i.setText(sse_)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        # Translating :D

        from pyrate import lang
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", lang[self.shortLang][9]))
        self.label.setText(_translate("Form", lang[self.shortLang][6]))
        self.label_2.setText(_translate("Form", lang[self.shortLang][5]))
        self.label_3.setText(_translate("Form", "Goldberg"))
        self.label_4.setText(_translate("Form", "SmartSteamEmu"))
        self.goldberg_i.setText(_translate("Form", "N/D"))
        self.smartsteamemu_i.setText(_translate("Form", "N/D"))
        self.pushButton.setText(_translate("Form", "(Re)Download"))
        self.pushButton_2.setText(_translate("Form", "(Re)Download"))
        

    def gb_install(self):
        from pyrate import debug
        from pyrate import lang
        try:
            os.rmdir(ins+pkgname_gb)
        except OSError:
            pass
        try:
            os.mkdir(ins+pkgname_gb)
        except OSError:
            if debug: print('Folder already exists, redownloading...')
        else:
            self.goldberg_i.setText(lang[self.shortLang][7])
            if debug: print('Folder created...')


        url = 'https://stngo.github.io/data-up/database/file/pyrate/gb.zip'
        r = requests.get(url, allow_redirects=True)
        open(ins+pkgname_gb+'/temp.zip', 'wb').write(r.content)

        with zf.ZipFile(ins+pkgname_gb+'/temp.zip') as installZip:
            installZip.extractall(ins+pkgname_gb)
        os.remove (ins+pkgname_gb+'/temp.zip')


    def sse_install(self):
        from pyrate import debug
        from pyrate import lang
        try:
            os.rmdir(ins+pkgname_sse)
        except OSError:
            pass
        try:
            os.mkdir(ins+pkgname_sse)
        except OSError:
            if debug: print('Folder already exists, redownloading...')
        else:
            self.smartsteamemu_i.setText(lang[self.shortLang][7])
            if debug: print('Folder created...')


        url = 'https://stngo.github.io/data-up/database/file/pyrate/sse.zip'
        r = requests.get(url, allow_redirects=True)
        open(ins+pkgname_sse+'/temp.zip', 'wb').write(r.content)

        with zf.ZipFile(ins+pkgname_sse+'/temp.zip') as installZip:
            installZip.extractall(ins+pkgname_sse)
        os.remove (ins+pkgname_sse+'/temp.zip')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
